

all:
	make -C l2fwd1b
	make -C l2fwd2b
	make -C nfvi
	make -C pcap
	make -C sfc


clean:
	make -C l2fwd1b  clean
	make -C l2fwd2b  clean
	make -C nfvi     clean
	make -C pcap     clean
	make -C sfc      clean
